# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mapCreatorGUI'
#
# Created: Fri Oct 10 11:49:39 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mapCreatorGUI.py'
#
# Created: Fri Oct 10 11:49:51 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mapCreatorGUI.ui'
#
# Created: Fri Oct 10 11:50:15 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MapCreator(object):
    def setupUi(self, MapCreator):
        MapCreator.setObjectName(_fromUtf8("MapCreator"))
        MapCreator.resize(723, 1222)
        MapCreator.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnCreateMaps = QtGui.QPushButton(MapCreator)
        self.btnCreateMaps.setGeometry(QtCore.QRect(240, 890, 221, 91))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnCreateMaps.setFont(font)
        self.btnCreateMaps.setObjectName(_fromUtf8("btnCreateMaps"))
        self.outputTextEdit = QtGui.QPlainTextEdit(MapCreator)
        self.outputTextEdit.setGeometry(QtCore.QRect(10, 990, 701, 221))
        self.outputTextEdit.setObjectName(_fromUtf8("outputTextEdit"))
        self.horizontalLayoutWidget = QtGui.QWidget(MapCreator)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 190, 701, 71))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnAddLayer = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.btnAddLayer.setObjectName(_fromUtf8("btnAddLayer"))
        self.horizontalLayout.addWidget(self.btnAddLayer)
        self.layerLocationLineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.layerLocationLineEdit.setObjectName(_fromUtf8("layerLocationLineEdit"))
        self.horizontalLayout.addWidget(self.layerLocationLineEdit)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(MapCreator)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 80, 701, 91))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btnSetTemplateLoc = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.btnSetTemplateLoc.setObjectName(_fromUtf8("btnSetTemplateLoc"))
        self.horizontalLayout_2.addWidget(self.btnSetTemplateLoc)
        self.templateLocLineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.templateLocLineEdit.setObjectName(_fromUtf8("templateLocLineEdit"))
        self.horizontalLayout_2.addWidget(self.templateLocLineEdit)
        self.label_3 = QtGui.QLabel(MapCreator)
        self.label_3.setGeometry(QtCore.QRect(200, 50, 391, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayoutWidget_3 = QtGui.QWidget(MapCreator)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 540, 701, 61))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.checkBoxKML = QtGui.QCheckBox(self.horizontalLayoutWidget_3)
        self.checkBoxKML.setObjectName(_fromUtf8("checkBoxKML"))
        self.horizontalLayout_3.addWidget(self.checkBoxKML)
        self.checkBoxLayer = QtGui.QCheckBox(self.horizontalLayoutWidget_3)
        self.checkBoxLayer.setObjectName(_fromUtf8("checkBoxLayer"))
        self.horizontalLayout_3.addWidget(self.checkBoxLayer)
        self.horizontalLayoutWidget_4 = QtGui.QWidget(MapCreator)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 640, 701, 91))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.btnSetUniqueLayerLoc = QtGui.QPushButton(self.horizontalLayoutWidget_4)
        self.btnSetUniqueLayerLoc.setObjectName(_fromUtf8("btnSetUniqueLayerLoc"))
        self.horizontalLayout_4.addWidget(self.btnSetUniqueLayerLoc)
        self.uniqueLayerLineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget_4)
        self.uniqueLayerLineEdit.setObjectName(_fromUtf8("uniqueLayerLineEdit"))
        self.horizontalLayout_4.addWidget(self.uniqueLayerLineEdit)
        self.label_5 = QtGui.QLabel(MapCreator)
        self.label_5.setGeometry(QtCore.QRect(220, 140, 491, 89))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_4 = QtGui.QLabel(MapCreator)
        self.label_4.setGeometry(QtCore.QRect(40, 0, 631, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_6 = QtGui.QLabel(MapCreator)
        self.label_6.setGeometry(QtCore.QRect(50, 480, 671, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayoutWidget_5 = QtGui.QWidget(MapCreator)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 790, 701, 91))
        self.horizontalLayoutWidget_5.setObjectName(_fromUtf8("horizontalLayoutWidget_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.btnSetDestDir = QtGui.QPushButton(self.horizontalLayoutWidget_5)
        self.btnSetDestDir.setObjectName(_fromUtf8("btnSetDestDir"))
        self.horizontalLayout_5.addWidget(self.btnSetDestDir)
        self.destDirLineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget_5)
        self.destDirLineEdit.setObjectName(_fromUtf8("destDirLineEdit"))
        self.horizontalLayout_5.addWidget(self.destDirLineEdit)
        self.label_7 = QtGui.QLabel(MapCreator)
        self.label_7.setGeometry(QtCore.QRect(140, 580, 491, 89))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(MapCreator)
        self.label_8.setGeometry(QtCore.QRect(90, 710, 531, 89))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.listLayers = QtGui.QListWidget(MapCreator)
        self.listLayers.setGeometry(QtCore.QRect(10, 310, 701, 161))
        self.listLayers.setObjectName(_fromUtf8("listLayers"))
        self.label_9 = QtGui.QLabel(MapCreator)
        self.label_9.setGeometry(QtCore.QRect(270, 240, 170, 89))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))

        self.retranslateUi(MapCreator)
        QtCore.QMetaObject.connectSlotsByName(MapCreator)

    def retranslateUi(self, MapCreator):
        MapCreator.setWindowTitle(_translate("MapCreator", "Map Creator", None))
        self.btnCreateMaps.setText(_translate("MapCreator", "Create Maps", None))
        self.btnAddLayer.setText(_translate("MapCreator", "Set Location", None))
        self.btnSetTemplateLoc.setText(_translate("MapCreator", "Set Location", None))
        self.label_3.setText(_translate("MapCreator", "Template Map Location", None))
        self.checkBoxKML.setText(_translate("MapCreator", "Create Layers from KML Files", None))
        self.checkBoxLayer.setText(_translate("MapCreator", "Use ESRI Layer Files", None))
        self.btnSetUniqueLayerLoc.setText(_translate("MapCreator", "Set Location", None))
        self.label_5.setText(_translate("MapCreator", "Add Underlying Layer", None))
        self.label_4.setText(_translate("MapCreator", "Layers that Persist Between Maps", None))
        self.label_6.setText(_translate("MapCreator", "Select Layer Unique to Each Map", None))
        self.btnSetDestDir.setText(_translate("MapCreator", "Set Location", None))
        self.label_7.setText(_translate("MapCreator", "Directory Containing KML Files", None))
        self.label_8.setText(_translate("MapCreator", "Select Destination Directory For Maps", None))
        self.label_9.setText(_translate("MapCreator", "Layers Added", None))

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mapCreatorGUI.ui'
#
# Created: Fri Oct 10 14:54:04 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MapCreator(object):
    def setupUi(self, MapCreator):
        MapCreator.setObjectName(_fromUtf8("MapCreator"))
        MapCreator.resize(723, 1222)
        MapCreator.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnCreateMaps = QtGui.QPushButton(MapCreator)
        self.btnCreateMaps.setGeometry(QtCore.QRect(250, 870, 221, 91))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnCreateMaps.setFont(font)
        self.btnCreateMaps.setObjectName(_fromUtf8("btnCreateMaps"))
        self.horizontalLayoutWidget = QtGui.QWidget(MapCreator)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 190, 701, 71))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnAddLayer = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.btnAddLayer.setObjectName(_fromUtf8("btnAddLayer"))
        self.horizontalLayout.addWidget(self.btnAddLayer)
        self.layerLocationLineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.layerLocationLineEdit.setObjectName(_fromUtf8("layerLocationLineEdit"))
        self.horizontalLayout.addWidget(self.layerLocationLineEdit)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(MapCreator)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 80, 701, 91))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btnSetTemplateLoc = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.btnSetTemplateLoc.setObjectName(_fromUtf8("btnSetTemplateLoc"))
        self.horizontalLayout_2.addWidget(self.btnSetTemplateLoc)
        self.templateLocLineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.templateLocLineEdit.setObjectName(_fromUtf8("templateLocLineEdit"))
        self.horizontalLayout_2.addWidget(self.templateLocLineEdit)
        self.label_3 = QtGui.QLabel(MapCreator)
        self.label_3.setGeometry(QtCore.QRect(200, 50, 391, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayoutWidget_3 = QtGui.QWidget(MapCreator)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 540, 701, 61))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.checkBoxKML = QtGui.QCheckBox(self.horizontalLayoutWidget_3)
        self.checkBoxKML.setObjectName(_fromUtf8("checkBoxKML"))
        self.horizontalLayout_3.addWidget(self.checkBoxKML)
        self.checkBoxLayer = QtGui.QCheckBox(self.horizontalLayoutWidget_3)
        self.checkBoxLayer.setObjectName(_fromUtf8("checkBoxLayer"))
        self.horizontalLayout_3.addWidget(self.checkBoxLayer)
        self.horizontalLayoutWidget_4 = QtGui.QWidget(MapCreator)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 640, 701, 91))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.btnSetUniqueLayerLoc = QtGui.QPushButton(self.horizontalLayoutWidget_4)
        self.btnSetUniqueLayerLoc.setObjectName(_fromUtf8("btnSetUniqueLayerLoc"))
        self.horizontalLayout_4.addWidget(self.btnSetUniqueLayerLoc)
        self.uniqueLayerLineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget_4)
        self.uniqueLayerLineEdit.setObjectName(_fromUtf8("uniqueLayerLineEdit"))
        self.horizontalLayout_4.addWidget(self.uniqueLayerLineEdit)
        self.label_5 = QtGui.QLabel(MapCreator)
        self.label_5.setGeometry(QtCore.QRect(220, 140, 491, 89))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_4 = QtGui.QLabel(MapCreator)
        self.label_4.setGeometry(QtCore.QRect(40, 0, 631, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_6 = QtGui.QLabel(MapCreator)
        self.label_6.setGeometry(QtCore.QRect(50, 480, 671, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayoutWidget_5 = QtGui.QWidget(MapCreator)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 790, 701, 91))
        self.horizontalLayoutWidget_5.setObjectName(_fromUtf8("horizontalLayoutWidget_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.btnSetDestDir = QtGui.QPushButton(self.horizontalLayoutWidget_5)
        self.btnSetDestDir.setObjectName(_fromUtf8("btnSetDestDir"))
        self.horizontalLayout_5.addWidget(self.btnSetDestDir)
        self.destDirLineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget_5)
        self.destDirLineEdit.setObjectName(_fromUtf8("destDirLineEdit"))
        self.horizontalLayout_5.addWidget(self.destDirLineEdit)
        self.label_7 = QtGui.QLabel(MapCreator)
        self.label_7.setGeometry(QtCore.QRect(140, 580, 491, 89))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(MapCreator)
        self.label_8.setGeometry(QtCore.QRect(90, 710, 531, 89))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.listLayers = QtGui.QListWidget(MapCreator)
        self.listLayers.setGeometry(QtCore.QRect(10, 310, 701, 161))
        self.listLayers.setObjectName(_fromUtf8("listLayers"))
        self.label_9 = QtGui.QLabel(MapCreator)
        self.label_9.setGeometry(QtCore.QRect(270, 240, 170, 89))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.logListWidget = QtGui.QListWidget(MapCreator)
        self.logListWidget.setGeometry(QtCore.QRect(10, 970, 701, 241))
        self.logListWidget.setObjectName(_fromUtf8("logListWidget"))

        self.retranslateUi(MapCreator)
        QtCore.QMetaObject.connectSlotsByName(MapCreator)

    def retranslateUi(self, MapCreator):
        MapCreator.setWindowTitle(_translate("MapCreator", "Map Creator", None))
        self.btnCreateMaps.setText(_translate("MapCreator", "Create Maps", None))
        self.btnAddLayer.setText(_translate("MapCreator", "Set Location", None))
        self.btnSetTemplateLoc.setText(_translate("MapCreator", "Set Location", None))
        self.label_3.setText(_translate("MapCreator", "Template Map Location", None))
        self.checkBoxKML.setText(_translate("MapCreator", "Create Layers from KML Files", None))
        self.checkBoxLayer.setText(_translate("MapCreator", "Use ESRI Layer Files", None))
        self.btnSetUniqueLayerLoc.setText(_translate("MapCreator", "Set Location", None))
        self.label_5.setText(_translate("MapCreator", "Add Underlying Layer", None))
        self.label_4.setText(_translate("MapCreator", "Layers that Persist Between Maps", None))
        self.label_6.setText(_translate("MapCreator", "Select Layer Unique to Each Map", None))
        self.btnSetDestDir.setText(_translate("MapCreator", "Set Location", None))
        self.label_7.setText(_translate("MapCreator", "Directory Containing KML Files", None))
        self.label_8.setText(_translate("MapCreator", "Select Destination Directory For Maps", None))
        self.label_9.setText(_translate("MapCreator", "Layers Added", None))

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mapCreatorGUI.ui'
#
# Created: Fri Oct 10 14:46:19 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MapCreator(object):
    def setupUi(self, MapCreator):
        MapCreator.setObjectName(_fromUtf8("MapCreator"))
        MapCreator.resize(723, 1222)
        MapCreator.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnCreateMaps = QtGui.QPushButton(MapCreator)
        self.btnCreateMaps.setGeometry(QtCore.QRect(250, 870, 221, 91))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnCreateMaps.setFont(font)
        self.btnCreateMaps.setObjectName(_fromUtf8("btnCreateMaps"))
        self.horizontalLayoutWidget = QtGui.QWidget(MapCreator)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 190, 701, 71))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnAddLayer = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.btnAddLayer.setObjectName(_fromUtf8("btnAddLayer"))
        self.horizontalLayout.addWidget(self.btnAddLayer)
        self.btnRemoveLayer = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.btnRemoveLayer.setObjectName(_fromUtf8("btnRemoveLayer"))
        self.horizontalLayout.addWidget(self.btnRemoveLayer)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(MapCreator)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 80, 701, 91))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btnSetTemplateLoc = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.btnSetTemplateLoc.setObjectName(_fromUtf8("btnSetTemplateLoc"))
        self.horizontalLayout_2.addWidget(self.btnSetTemplateLoc)
        self.templateLocLineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.templateLocLineEdit.setObjectName(_fromUtf8("templateLocLineEdit"))
        self.horizontalLayout_2.addWidget(self.templateLocLineEdit)
        self.label_3 = QtGui.QLabel(MapCreator)
        self.label_3.setGeometry(QtCore.QRect(200, 50, 391, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayoutWidget_3 = QtGui.QWidget(MapCreator)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 540, 701, 61))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.checkBoxKML = QtGui.QCheckBox(self.horizontalLayoutWidget_3)
        self.checkBoxKML.setObjectName(_fromUtf8("checkBoxKML"))
        self.horizontalLayout_3.addWidget(self.checkBoxKML)
        self.checkBoxLayer = QtGui.QCheckBox(self.horizontalLayoutWidget_3)
        self.checkBoxLayer.setObjectName(_fromUtf8("checkBoxLayer"))
        self.horizontalLayout_3.addWidget(self.checkBoxLayer)
        self.horizontalLayoutWidget_4 = QtGui.QWidget(MapCreator)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 640, 701, 91))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.btnSetUniqueLayerLoc = QtGui.QPushButton(self.horizontalLayoutWidget_4)
        self.btnSetUniqueLayerLoc.setObjectName(_fromUtf8("btnSetUniqueLayerLoc"))
        self.horizontalLayout_4.addWidget(self.btnSetUniqueLayerLoc)
        self.uniqueLayerLineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget_4)
        self.uniqueLayerLineEdit.setObjectName(_fromUtf8("uniqueLayerLineEdit"))
        self.horizontalLayout_4.addWidget(self.uniqueLayerLineEdit)
        self.label_4 = QtGui.QLabel(MapCreator)
        self.label_4.setGeometry(QtCore.QRect(40, 0, 631, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_6 = QtGui.QLabel(MapCreator)
        self.label_6.setGeometry(QtCore.QRect(50, 480, 671, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayoutWidget_5 = QtGui.QWidget(MapCreator)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 790, 701, 91))
        self.horizontalLayoutWidget_5.setObjectName(_fromUtf8("horizontalLayoutWidget_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.btnSetDestDir = QtGui.QPushButton(self.horizontalLayoutWidget_5)
        self.btnSetDestDir.setObjectName(_fromUtf8("btnSetDestDir"))
        self.horizontalLayout_5.addWidget(self.btnSetDestDir)
        self.destDirLineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget_5)
        self.destDirLineEdit.setObjectName(_fromUtf8("destDirLineEdit"))
        self.horizontalLayout_5.addWidget(self.destDirLineEdit)
        self.label_7 = QtGui.QLabel(MapCreator)
        self.label_7.setGeometry(QtCore.QRect(140, 580, 491, 89))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(MapCreator)
        self.label_8.setGeometry(QtCore.QRect(90, 710, 531, 89))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.listLayers = QtGui.QListWidget(MapCreator)
        self.listLayers.setGeometry(QtCore.QRect(10, 300, 701, 171))
        self.listLayers.setObjectName(_fromUtf8("listLayers"))
        self.label_9 = QtGui.QLabel(MapCreator)
        self.label_9.setGeometry(QtCore.QRect(270, 230, 170, 89))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.logListWidget = QtGui.QListWidget(MapCreator)
        self.logListWidget.setGeometry(QtCore.QRect(10, 970, 701, 241))
        self.logListWidget.setObjectName(_fromUtf8("logListWidget"))
        self.label_5 = QtGui.QLabel(MapCreator)
        self.label_5.setGeometry(QtCore.QRect(220, 140, 271, 69))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))

        self.retranslateUi(MapCreator)
        QtCore.QMetaObject.connectSlotsByName(MapCreator)

    def retranslateUi(self, MapCreator):
        MapCreator.setWindowTitle(_translate("MapCreator", "Map Creator", None))
        self.btnCreateMaps.setText(_translate("MapCreator", "Create Maps", None))
        self.btnAddLayer.setText(_translate("MapCreator", "Select a Layer to Add", None))
        self.btnRemoveLayer.setText(_translate("MapCreator", "Remove a Layer", None))
        self.btnSetTemplateLoc.setText(_translate("MapCreator", "Set Location", None))
        self.label_3.setText(_translate("MapCreator", "Template Map Location", None))
        self.checkBoxKML.setText(_translate("MapCreator", "Create Layers from KML Files", None))
        self.checkBoxLayer.setText(_translate("MapCreator", "Use ESRI Layer Files", None))
        self.btnSetUniqueLayerLoc.setText(_translate("MapCreator", "Set Location", None))
        self.label_4.setText(_translate("MapCreator", "Layers that Persist Between Maps", None))
        self.label_6.setText(_translate("MapCreator", "Select Layer Unique to Each Map", None))
        self.btnSetDestDir.setText(_translate("MapCreator", "Set Location", None))
        self.label_7.setText(_translate("MapCreator", "Directory Containing KML Files", None))
        self.label_8.setText(_translate("MapCreator", "Select Destination Directory For Maps", None))
        self.label_9.setText(_translate("MapCreator", "Map Layers", None))
        self.label_5.setText(_translate("MapCreator", "Add Underlying Layers", None))

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mapCreatorGUI'
#
# Created: Fri Oct 10 15:36:56 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mapCreatorGUI.ui'
#
# Created: Fri Oct 10 15:37:04 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MapCreator(object):
    def setupUi(self, MapCreator):
        MapCreator.setObjectName(_fromUtf8("MapCreator"))
        MapCreator.resize(723, 1222)
        MapCreator.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnCreateMaps = QtGui.QPushButton(MapCreator)
        self.btnCreateMaps.setGeometry(QtCore.QRect(250, 870, 221, 91))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnCreateMaps.setFont(font)
        self.btnCreateMaps.setObjectName(_fromUtf8("btnCreateMaps"))
        self.horizontalLayoutWidget = QtGui.QWidget(MapCreator)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 190, 701, 71))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnAddLayer = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.btnAddLayer.setObjectName(_fromUtf8("btnAddLayer"))
        self.horizontalLayout.addWidget(self.btnAddLayer)
        self.btnRemoveLayer = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.btnRemoveLayer.setObjectName(_fromUtf8("btnRemoveLayer"))
        self.horizontalLayout.addWidget(self.btnRemoveLayer)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(MapCreator)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 80, 701, 91))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btnSetTemplateLoc = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.btnSetTemplateLoc.setObjectName(_fromUtf8("btnSetTemplateLoc"))
        self.horizontalLayout_2.addWidget(self.btnSetTemplateLoc)
        self.templateLocLineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.templateLocLineEdit.setObjectName(_fromUtf8("templateLocLineEdit"))
        self.horizontalLayout_2.addWidget(self.templateLocLineEdit)
        self.label_3 = QtGui.QLabel(MapCreator)
        self.label_3.setGeometry(QtCore.QRect(200, 50, 391, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayoutWidget_3 = QtGui.QWidget(MapCreator)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 540, 701, 61))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.checkBoxKML = QtGui.QCheckBox(self.horizontalLayoutWidget_3)
        self.checkBoxKML.setObjectName(_fromUtf8("checkBoxKML"))
        self.horizontalLayout_3.addWidget(self.checkBoxKML)
        self.checkBoxLayer = QtGui.QCheckBox(self.horizontalLayoutWidget_3)
        self.checkBoxLayer.setObjectName(_fromUtf8("checkBoxLayer"))
        self.horizontalLayout_3.addWidget(self.checkBoxLayer)
        self.horizontalLayoutWidget_4 = QtGui.QWidget(MapCreator)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 640, 701, 91))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.btnSetUniqueLayerLoc = QtGui.QPushButton(self.horizontalLayoutWidget_4)
        self.btnSetUniqueLayerLoc.setObjectName(_fromUtf8("btnSetUniqueLayerLoc"))
        self.horizontalLayout_4.addWidget(self.btnSetUniqueLayerLoc)
        self.uniqueLayerLineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget_4)
        self.uniqueLayerLineEdit.setObjectName(_fromUtf8("uniqueLayerLineEdit"))
        self.horizontalLayout_4.addWidget(self.uniqueLayerLineEdit)
        self.label_4 = QtGui.QLabel(MapCreator)
        self.label_4.setGeometry(QtCore.QRect(40, 0, 631, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_6 = QtGui.QLabel(MapCreator)
        self.label_6.setGeometry(QtCore.QRect(50, 480, 671, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayoutWidget_5 = QtGui.QWidget(MapCreator)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 790, 701, 91))
        self.horizontalLayoutWidget_5.setObjectName(_fromUtf8("horizontalLayoutWidget_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.btnSetDestDir = QtGui.QPushButton(self.horizontalLayoutWidget_5)
        self.btnSetDestDir.setObjectName(_fromUtf8("btnSetDestDir"))
        self.horizontalLayout_5.addWidget(self.btnSetDestDir)
        self.destDirLineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget_5)
        self.destDirLineEdit.setObjectName(_fromUtf8("destDirLineEdit"))
        self.horizontalLayout_5.addWidget(self.destDirLineEdit)
        self.uniqueLayerLabel = QtGui.QLabel(MapCreator)
        self.uniqueLayerLabel.setGeometry(QtCore.QRect(140, 580, 491, 89))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.uniqueLayerLabel.setFont(font)
        self.uniqueLayerLabel.setObjectName(_fromUtf8("uniqueLayerLabel"))
        self.label_8 = QtGui.QLabel(MapCreator)
        self.label_8.setGeometry(QtCore.QRect(90, 710, 531, 89))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.listLayers = QtGui.QListWidget(MapCreator)
        self.listLayers.setGeometry(QtCore.QRect(10, 300, 701, 171))
        self.listLayers.setObjectName(_fromUtf8("listLayers"))
        self.label_9 = QtGui.QLabel(MapCreator)
        self.label_9.setGeometry(QtCore.QRect(270, 230, 170, 89))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.logListWidget = QtGui.QListWidget(MapCreator)
        self.logListWidget.setGeometry(QtCore.QRect(10, 970, 701, 241))
        self.logListWidget.setObjectName(_fromUtf8("logListWidget"))
        self.label_5 = QtGui.QLabel(MapCreator)
        self.label_5.setGeometry(QtCore.QRect(220, 140, 271, 69))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))

        self.retranslateUi(MapCreator)
        QtCore.QMetaObject.connectSlotsByName(MapCreator)

    def retranslateUi(self, MapCreator):
        MapCreator.setWindowTitle(_translate("MapCreator", "Map Creator", None))
        self.btnCreateMaps.setText(_translate("MapCreator", "Create Maps", None))
        self.btnAddLayer.setText(_translate("MapCreator", "Select a Layer to Add", None))
        self.btnRemoveLayer.setText(_translate("MapCreator", "Remove a Layer", None))
        self.btnSetTemplateLoc.setText(_translate("MapCreator", "Set Location", None))
        self.label_3.setText(_translate("MapCreator", "Template Map Location", None))
        self.checkBoxKML.setText(_translate("MapCreator", "Create Layers from KML Files", None))
        self.checkBoxLayer.setText(_translate("MapCreator", "Use ESRI Layer Files", None))
        self.btnSetUniqueLayerLoc.setText(_translate("MapCreator", "Set Location", None))
        self.label_4.setText(_translate("MapCreator", "Layers that Persist Between Maps", None))
        self.label_6.setText(_translate("MapCreator", "Select Layer Unique to Each Map", None))
        self.btnSetDestDir.setText(_translate("MapCreator", "Set Location", None))
        self.uniqueLayerLabel.setText(_translate("MapCreator", "Directory Containing KML Files", None))
        self.label_8.setText(_translate("MapCreator", "Select Destination Directory For Maps", None))
        self.label_9.setText(_translate("MapCreator", "Map Layers", None))
        self.label_5.setText(_translate("MapCreator", "Add Underlying Layers", None))

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mapCreatorGUI.ui'
#
# Created: Fri Oct 10 15:41:20 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MapCreator(object):
    def setupUi(self, MapCreator):
        MapCreator.setObjectName(_fromUtf8("MapCreator"))
        MapCreator.resize(723, 1222)
        MapCreator.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnCreateMaps = QtGui.QPushButton(MapCreator)
        self.btnCreateMaps.setGeometry(QtCore.QRect(250, 870, 221, 91))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnCreateMaps.setFont(font)
        self.btnCreateMaps.setObjectName(_fromUtf8("btnCreateMaps"))
        self.horizontalLayoutWidget = QtGui.QWidget(MapCreator)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 190, 701, 71))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnAddLayer = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.btnAddLayer.setObjectName(_fromUtf8("btnAddLayer"))
        self.horizontalLayout.addWidget(self.btnAddLayer)
        self.btnRemoveLayer = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.btnRemoveLayer.setObjectName(_fromUtf8("btnRemoveLayer"))
        self.horizontalLayout.addWidget(self.btnRemoveLayer)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(MapCreator)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 80, 701, 91))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btnSetTemplateLoc = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.btnSetTemplateLoc.setObjectName(_fromUtf8("btnSetTemplateLoc"))
        self.horizontalLayout_2.addWidget(self.btnSetTemplateLoc)
        self.templateLocLineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.templateLocLineEdit.setObjectName(_fromUtf8("templateLocLineEdit"))
        self.horizontalLayout_2.addWidget(self.templateLocLineEdit)
        self.label_3 = QtGui.QLabel(MapCreator)
        self.label_3.setGeometry(QtCore.QRect(200, 50, 391, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayoutWidget_3 = QtGui.QWidget(MapCreator)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 540, 701, 61))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.checkBoxKML = QtGui.QCheckBox(self.horizontalLayoutWidget_3)
        self.checkBoxKML.setObjectName(_fromUtf8("checkBoxKML"))
        self.horizontalLayout_3.addWidget(self.checkBoxKML)
        self.checkBoxLayer = QtGui.QCheckBox(self.horizontalLayoutWidget_3)
        self.checkBoxLayer.setObjectName(_fromUtf8("checkBoxLayer"))
        self.horizontalLayout_3.addWidget(self.checkBoxLayer)
        self.horizontalLayoutWidget_4 = QtGui.QWidget(MapCreator)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 640, 701, 91))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.btnSetUniqueLayerLoc = QtGui.QPushButton(self.horizontalLayoutWidget_4)
        self.btnSetUniqueLayerLoc.setObjectName(_fromUtf8("btnSetUniqueLayerLoc"))
        self.horizontalLayout_4.addWidget(self.btnSetUniqueLayerLoc)
        self.uniqueLayerLineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget_4)
        self.uniqueLayerLineEdit.setObjectName(_fromUtf8("uniqueLayerLineEdit"))
        self.horizontalLayout_4.addWidget(self.uniqueLayerLineEdit)
        self.label_4 = QtGui.QLabel(MapCreator)
        self.label_4.setGeometry(QtCore.QRect(40, 0, 631, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_6 = QtGui.QLabel(MapCreator)
        self.label_6.setGeometry(QtCore.QRect(50, 480, 671, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayoutWidget_5 = QtGui.QWidget(MapCreator)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 790, 701, 91))
        self.horizontalLayoutWidget_5.setObjectName(_fromUtf8("horizontalLayoutWidget_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.btnSetDestDir = QtGui.QPushButton(self.horizontalLayoutWidget_5)
        self.btnSetDestDir.setObjectName(_fromUtf8("btnSetDestDir"))
        self.horizontalLayout_5.addWidget(self.btnSetDestDir)
        self.destDirLineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget_5)
        self.destDirLineEdit.setObjectName(_fromUtf8("destDirLineEdit"))
        self.horizontalLayout_5.addWidget(self.destDirLineEdit)
        self.uniqueLayerLabel = QtGui.QLabel(MapCreator)
        self.uniqueLayerLabel.setGeometry(QtCore.QRect(140, 580, 491, 89))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.uniqueLayerLabel.setFont(font)
        self.uniqueLayerLabel.setObjectName(_fromUtf8("uniqueLayerLabel"))
        self.label_8 = QtGui.QLabel(MapCreator)
        self.label_8.setGeometry(QtCore.QRect(90, 710, 531, 89))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.listLayers = QtGui.QListWidget(MapCreator)
        self.listLayers.setGeometry(QtCore.QRect(10, 300, 701, 171))
        self.listLayers.setObjectName(_fromUtf8("listLayers"))
        self.label_9 = QtGui.QLabel(MapCreator)
        self.label_9.setGeometry(QtCore.QRect(270, 230, 170, 89))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.logListWidget = QtGui.QListWidget(MapCreator)
        self.logListWidget.setGeometry(QtCore.QRect(10, 970, 701, 241))
        self.logListWidget.setObjectName(_fromUtf8("logListWidget"))
        self.label_5 = QtGui.QLabel(MapCreator)
        self.label_5.setGeometry(QtCore.QRect(220, 140, 271, 69))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))

        self.retranslateUi(MapCreator)
        QtCore.QMetaObject.connectSlotsByName(MapCreator)

    def retranslateUi(self, MapCreator):
        MapCreator.setWindowTitle(_translate("MapCreator", "Map Creator", None))
        self.btnCreateMaps.setText(_translate("MapCreator", "Create Maps", None))
        self.btnAddLayer.setText(_translate("MapCreator", "Select a Layer to Add", None))
        self.btnRemoveLayer.setText(_translate("MapCreator", "Remove a Layer", None))
        self.btnSetTemplateLoc.setText(_translate("MapCreator", "Set Location", None))
        self.label_3.setText(_translate("MapCreator", "Template Map Location", None))
        self.checkBoxKML.setText(_translate("MapCreator", "Create Layers from KML Files", None))
        self.checkBoxLayer.setText(_translate("MapCreator", "Use ESRI Layer Files", None))
        self.btnSetUniqueLayerLoc.setText(_translate("MapCreator", "Set Location", None))
        self.label_4.setText(_translate("MapCreator", "Layers that Persist Between Maps", None))
        self.label_6.setText(_translate("MapCreator", "Select Layer Unique to Each Map", None))
        self.btnSetDestDir.setText(_translate("MapCreator", "Set Location", None))
        self.uniqueLayerLabel.setText(_translate("MapCreator", "Directory Containing Layer Files", None))
        self.label_8.setText(_translate("MapCreator", "Select Destination Directory For Maps", None))
        self.label_9.setText(_translate("MapCreator", "Map Layers", None))
        self.label_5.setText(_translate("MapCreator", "Add Underlying Layers", None))

